---
- name: create config folder
  file:
    path: "{{ v2ray_config_path }}"
    state: directory
    mode: 0744

- name: install v2ray (docker)
  include_tasks: docker.yml
  when: v2ray_install_type == 'docker'

- name: install v2ray (native)
  include_tasks: native.yml
  when: v2ray_install_type == 'native'

- name: config
  template:
    src: config.json.j2
    dest: "{{ v2ray_config_path }}/config.json"
    mode: 0644
  notify:
    - restart v2ray
